version: '3.9'

services:
  trinitt_backend:
    container_name: "trinitt_cluster"
    image: "trinitt_cluster"
    build:
      context: .
      target: ${TARGET}
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT} 
    volumes:
      - .:/app  
